spring:
    application:
        name: hotmart-voices
    main:
        allow-bean-definition-overriding: false
        banner-mode: false
    jackson:
        default-property-inclusion: non_null
        deserialization:
            fail-on-unknown-properties: false
server:
    compression:
        enabled: true
        mime-types: text/html,text/css,application/javascript,application/json
        min-response-size: 2048
    port: ${PORT:8080}
    servlet:
        context-path: /
management:
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: info, health, metrics
security:
    user:
        name: hotmart
        role: ACTUATOR
feign:
    default:
        connectTimeout: 30000
        readTimeout: 30000
    client:
        api-reshape: https://app.reshape.com.br
        api-eleven: https://api.elevenlabs.io
    httpclient:
        disable-ssl-validation: true
reshape:
    key: b612cba261098e02e0138bcb6716e3360059e024
    apiUrl: https://app.reshape.com.br
    pathTranscription: /api/v1/transcriptions/
eleven:
    key: e7d14ac60d14139a4212b7fbc7565aac
    voiceId: ErXwobaYiN019PkySvjV
    apiUrl: https://api.elevenlabs.io
    path: /v1/text-to-speech/
    model: eleven_multilingual_v2
    stability: 0.9
    similarity_boost: 0.9
hotmert:
    s3:
        bucket: https://staging-hotmart.s3.amazonaws.com/hackweek11/audio/
