name: deploy-staging
permissions: write-all
on:
  push:
    branches:
      - master

concurrency:
  group: pipeline-staging-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  base:
    uses: Hotmart-Org/actions/.github/workflows/base.yaml@master
    secrets: inherit
    with:
      runs-on: "buildstaging-enterprise-iac"
      file: "staging.yml"
      environment: "staging"
      cluster: "buildstaging"
      namespace: "hackweek"
  pipeline-staging:
    runs-on: [ self-hosted, buildstaging-enterprise-iac ]
    needs: base
    env:
      AWS_DEFAULT_REGION: us-east-1
      VAULT_ROLE: "ga"
      JAVA_VERSION: "21"
    steps:
      - name: clone-application
        uses: actions/checkout@v3

      - name: Configure Artifactory
        uses: Hotmart-Org/actions/codeartifact@master
        with:
          type: 'java'

      - name: restore-cache
        uses: Hotmart-Org/actions/cache@master
        with:
          bucket: buildstaging-pipeline-cache
          cache-key: "${{ hashFiles('pom.xml') }}"
          restore: true
          mount: .m2, .gradle-wrapper
        env:
          GH_TOKEN: ${{ secrets.CI_GH_TOKEN }}

      - name: Configure Artifactory
        uses: Hotmart-Org/actions/codeartifact@master
        with:
          type: 'java'

      - name: Install Java
        id: install-java
        uses: actions/setup-java@v3
        with:
          java-version: "21.0.1+12.0.LTS"
          distribution: "adopt"

      - name: build-application
        env:
          GRADLE_USER_HOME: .gradle-wrapper
        run: |
          ./gradlew clean assemble -x test    

      - name: save-cache
        uses: Hotmart-Org/actions/cache@master
        with:
          bucket: 'buildstaging-pipeline-cache'
          rebuild: true
          mount: .gradle-wrapper,.m2
          cache-key: '{{ checksum "build.gradle" }}'

      - name: build-image
        uses: Hotmart-Org/actions/docker@master
        with:
          file: "staging.yml"

      - name: deploy-application
        uses: Hotmart-Org/actions/helm@master
        with:
          file: "staging.yml"
          environment: "staging"
          cluster: "buildstaging"
          namespace: "hackweek"